ASP_GCH1108/Models/JobList.cs
using Microsoft.AspNetCore.Identity;
using Newtonsoft.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ASP_GCH1108.Models
{
    public class JobList
    {
        [Key]
        public int JobId { get; set; }
        [Required]
        public string JobTitle { get; set; }
        [Required]
        public string JobDescription { get; set; }
        [Required]
        public string RequiredProfiles { get; set; }
        [Required]
        public DateTime ApplicationDeadline { get; set; }
        public bool status { get; set; } = false;

        //User Id
        public string? UserId { get; set; }
        [ForeignKey("UserId")]
        public IdentityUser? User { get; set; }
        public string? UserName { get; set; }

        //Connect
        public ICollection<JobApplication>? Application { get; set; }
    }
}

ASP_GCH1108/Controllers/JobApplicationsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ASP_GCH1108.Data;
using ASP_GCH1108.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

namespace ASP_GCH1108.Controllers
{
    public class JobApplicationsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public JobApplicationsController(ApplicationDbContext context, UserManager<IdentityUser> userManager, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _userManager = userManager;
            _webHostEnvironment = webHostEnvironment;
        }

        [Authorize(Roles = "JobSeeker")]
        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);
            var userApplications = _context.JobApplication
                                          .Include(j => j.JobList)
                                          //.Include(j => j.Qualification)
                                          .Include(j => j.User)
                                          .Where(j => j.UserId == userId);
            return View(await userApplications.ToListAsync());
        }

        [Authorize(Roles = "Employer")]
        public async Task<IActionResult> EmployerView()
        {
            var userId = _userManager.GetUserId(User);

            // Fetch JobIds that belong to the current Employer
            var employerJobIds = await _context.JobList
                                               .Where(j => j.UserId == userId)
                                               .Select(j => j.JobId)
                                               .ToListAsync();

            // Fetch JobApplications that have JobIds in the employerJobIds list
            var employerApplications = await _context.JobApplication
                                                     .Include(j => j.JobList)
                                                     //.Include(j => j.Qualification)
                                                     .Include(j => j.User)
                                                     .Where(j => employerJobIds.Contains(j.JobId))
                                                     .ToListAsync();

            return View(employerApplications);
        }


        [Authorize(Roles = "JobSeeker")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jobApplication = await _context.JobApplication
                                               .Include(j => j.JobList)
                                               //.Include(j => j.Qualification)
                                               .Include(j => j.User)
                                               .FirstOrDefaultAsync(m => m.ApplicationId == id);
            if (jobApplication == null)
            {
                return NotFound();
            }

            return View(jobApplication);
        }

        [Authorize(Roles = "Employer")]
        public async Task<IActionResult> DetailEmployer(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jobApplication = await _context.JobApplication
                                               .Include(j => j.JobList)
                                               //.Include(j => j.Qualification)
                                               .Include(j => j.User)
                                               .FirstOrDefaultAsync(m => m.ApplicationId == id);

            if (jobApplication == null)
            {
                return NotFound();
            }

            var userId = _userManager.GetUserId(User);
            var employerJobIds = await _context.JobList
                                               .Where(j => j.UserId == userId)
                                               .Select(j => j.JobId)
                                               .ToListAsync();

            if (!employerJobIds.Contains(jobApplication.JobId))
            {
                return Forbid();
            }

            return View(jobApplication);
        }


        [Authorize(Roles = "JobSeeker")]
        public IActionResult Create(int jobId)
        {
            ViewData["JobId"] = jobId;
            ViewData["ProfileId"] = new SelectList(_context.Profile, "ProfileId", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "JobSeeker")]
        public async Task<IActionResult> Create(JobApplication jobApplication, int jobId)
        {
            if (ModelState.IsValid)
            {
                jobApplication.Status = false;
                jobApplication.JobId = jobId;
                jobApplication.UserId = _userManager.GetUserId(User);

                if (jobApplication.Picture != null)
                {
                    jobApplication.UrlImage = UploadedFile(jobApplication);
                }

                _context.Add(jobApplication);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["JobId"] = jobId;
            //ViewData["QualificationId"] = new SelectList(_context.Qualification, "QualificationId", "Name", jobApplication.QualificationId);
            return View(jobApplication);
        }
        private string UploadedFile(JobApplication model)
        {
            string uniqueFileName = "";
            if (model.Picture != null)
            {
                string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Picture.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.Picture.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }

        [Authorize(Roles = "JobSeeker")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jobApplication = await _context.JobApplication.FindAsync(id);
            if (jobApplication == null)
            {
                return NotFound();
            }
            ViewData["JobList"] = jobApplication.JobList;
            ViewData["JobId"] = jobApplication.JobId;
            //ViewData["QualificationId"] = new SelectList(_context.Profile, "QualificationId", "Name", jobApplication.QualificationId);
            return View(jobApplication);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "JobSeeker")]
        public async Task<IActionResult> Edit(int id,JobApplication jobApplication)
        {
            if (id != jobApplication.ApplicationId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (jobApplication.Picture != null)
                    {
                        jobApplication.UrlImage = UploadedFile(jobApplication);
                    }
                    _context.Update(jobApplication);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JobApplicationExists(jobApplication.ApplicationId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            //ViewData["QualificationId"] = new SelectList(_context.Qualification, "QualificationId", "DegreeType", jobApplication.QualificationId);
            return View(jobApplication);
        }

        [Authorize(Roles = "JobSeeker")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jobApplication = await _context.JobApplication
                                               .Include(j => j.JobList)
                                               //.Include(j => j.Qualification)
                                               .Include(j => j.User)
                                               .FirstOrDefaultAsync(m => m.ApplicationId == id);
            if (jobApplication == null)
            {
                return NotFound();
            }

            return View(jobApplication);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "JobSeeker")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var jobApplication = await _context.JobApplication.FindAsync(id);
            _context.JobApplication.Remove(jobApplication);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Employer")]
        public async Task<IActionResult> DeleteEP(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jobApplication = await _context.JobApplication
                                               .Include(j => j.JobList)

ASP_GCH1108/Controllers/JobListsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using ASP_GCH1108.Data;
using ASP_GCH1108.Models;
using Microsoft.AspNetCore.Authorization;

public class JobListsController : Controller
{
    private readonly UserManager<IdentityUser> _userManager;
    private readonly ApplicationDbContext _context;

    public JobListsController(UserManager<IdentityUser> userManager, ApplicationDbContext context)
    {
        _userManager = userManager;
        _context = context;
    }

    [Authorize(Roles = "Employer")]
    public async Task<IActionResult> Index()
    {
        string UserName = _userManager.GetUserName(User);
        var jobLists = await _context.JobList.Where(j => j.UserName.Equals(UserName)).ToListAsync();
        return View(jobLists);
    }

    [Authorize(Roles = "JobSeeker")]
    public async Task<IActionResult> AvailableJobs()
    {
        var jobLists = await _context.JobList.Where(j => j.status).ToListAsync();
        return View(jobLists);
    }

    [Authorize(Roles = "Employer")]
    public IActionResult Create()
    {
        return View();
    }

    [Authorize(Roles = "Employer")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(JobList jobList)
    {
        if (ModelState.IsValid)
        {
            jobList.UserId = _userManager.GetUserId(User);
            jobList.UserName = _userManager.GetUserName(User);
            jobList.status = false;
            _context.Add(jobList);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        return View(jobList);
    }

    [Authorize(Roles = "Employer")]
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var jobList = await _context.JobList.FindAsync(id);
        if (jobList == null)
        {
            return NotFound();
        }
        return View(jobList);
    }

    [Authorize(Roles = "Employer")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("JobId,JobTitle,JobDescription,RequiredQualifications,ApplicationDeadline")] JobList jobList)
    {
        if (id != jobList.JobId)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                var existingJob = await _context.JobList.FindAsync(id);
                if (existingJob == null)
                {
                    return NotFound();
                }

                existingJob.JobTitle = jobList.JobTitle;
                existingJob.JobDescription = jobList.JobDescription;
                existingJob.RequiredProfiles = jobList.RequiredProfiles;
                existingJob.ApplicationDeadline = jobList.ApplicationDeadline;

                _context.Update(existingJob);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!JobListExists(jobList.JobId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        return View(jobList);
    }

    [Authorize(Roles = "Employer")]
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var jobList = await _context.JobList
            .FirstOrDefaultAsync(m => m.JobId == id);
        if (jobList == null)
        {
            return NotFound();
        }

        return View(jobList);
    }

    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = "Employer")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var jobList = await _context.JobList.FindAsync(id);
        _context.JobList.Remove(jobList);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Allow(int id)
    {
        var jobList = await _context.JobList.FindAsync(id);
        if (jobList == null)
        {
            return NotFound();
        }

        jobList.status = true;
        _context.Update(jobList);
        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(AdminManager));
    }

    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> DetailsAdmin(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var jobList = await _context.JobList
            .FirstOrDefaultAsync(m => m.JobId == id);
        if (jobList == null)
        {
            return NotFound();
        }

        return View(jobList);
    }

    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> AdminManager()
    {
        return View(await _context.JobList.Where(j => j.status == false).ToListAsync());
    }

    [HttpPost, ActionName("AdminDeleteConfirmed")]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> AdminDeleteConfirmed(int id)
    {
        var jobList = await _context.JobList.FindAsync(id);
        _context.JobList.Remove(jobList);
        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(AdminManager));
    }

    private bool JobListExists(int id)
    {
        return _context.JobList.Any(e => e.JobId == id);
    }
}

ASP_GCH1108/Views/JobLists/AdminManager.cshtml
@model IEnumerable<JobList>

@{
    ViewData["Title"] = "Job List";
}

<h2>Job List</h2>

<table class="table table-striped table-bordered">
    <thead class="thead-dark">
        <tr>
            <th>
                UserName of Employer
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobTitle)
            </th>
            <th>
                Status
            </th>
            <th>
                Function
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.JobTitle)
                </td>
                <td>
                    @(item.status ? "Allowed" : "Not Allowed")
                </td>
                <td>
                    <a asp-action="Allow" asp-route-id="@item.JobId" class="btn btn-primary">Accept</a>
                    <a asp-action="DetailsAdmin" asp-route-id="@item.JobId" class="btn btn-info">Details</a>
                    <form asp-action="AdminDeleteConfirmed" method="post" style="display:inline;">
                        <input type="hidden" name="id" value="@item.JobId" />
                        <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this job?');">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

ASP_GCH1108/Views/JobLists/Allow.cshtml
<form asp-action="Allow" method="post">
    <input type="hidden" name="id" value="@Model.JobId" />
    <button type="submit">Allow</button>
</form>

ASP_GCH1108/Views/JobLists/AvailableJobs.cshtml
@model IEnumerable<ASP_GCH1108.Models.JobList>

@{
    ViewData["Title"] = "Available Jobs";
}

<h2>@ViewData["Title"]</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Job Title</th>
            <th>Job Description</th>
            <th>Required Qualifications</th>
            <th>Application Deadline</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.JobTitle)</td>
                <td>@Html.DisplayFor(modelItem => item.JobDescription)</td>
                <td>@Html.DisplayFor(modelItem => item.RequiredProfiles)</td>
                <td>@Html.DisplayFor(modelItem => item.ApplicationDeadline)</td>
                <td>
                    <a class="btn btn-primary" asp-action="Create" asp-controller="JobApplications" asp-route-jobId="@item.JobId">Apply</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<br />
<br />
<br />

ASP_GCH1108/Views/JobLists/Create.cshtml
@model JobList

@{
    ViewData["Title"] = "Create Job";
}

<h2 class="my-4">Create Job</h2>

<form asp-action="Create" method="post" class="needs-validation" novalidate>
    <div class="mb-3">
        <label asp-for="JobTitle" class="form-label">Job Title</label>
        <input asp-for="JobTitle" class="form-control" required />
        <div class="invalid-feedback">
            @Html.ValidationMessageFor(model => model.JobTitle)
        </div>
    </div>
    <div class="mb-3">
        <label asp-for="JobDescription" class="form-label">Job Description</label>
        <input asp-for="JobDescription" class="form-control" required />
        <div class="invalid-feedback">
            @Html.ValidationMessageFor(model => model.JobDescription)
        </div>
    </div>
    <div class="mb-3">
        <label asp-for="RequiredProfiles" class="form-label">Required Profiles</label>
        <input asp-for="RequiredProfiles" class="form-control" required />
        <div class="invalid-feedback">
            @Html.ValidationMessageFor(model => model.RequiredProfiles)
        </div>
    </div>
    <div class="mb-3">
        <label asp-for="ApplicationDeadline" class="form-label">Application Deadline</label>
        <input asp-for="ApplicationDeadline" class="form-control" type="date" required />
        <div class="invalid-feedback">
            @Html.ValidationMessageFor(model => model.ApplicationDeadline)
        </div>
    </div>
    <div class="mb-3">
        <button type="submit" class="btn btn-primary">Create</button>
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </div>
</form>
<br />
<br /><br />

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        (function () {
            'use strict';
            window.addEventListener('load', function () {
                var forms = document.getElementsByClassName('needs-validation');
                var validation = Array.prototype.filter.call(forms, function (form) {
                    form.addEventListener('submit', function (event) {
                        if (form.checkValidity() === false) {
                            event.preventDefault();
                            event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                    }, false);
                });
            }, false);
        })();
    </script>
}

ASP_GCH1108/Views/JobLists/Delete.cshtml
@model JobList

@{
    ViewData["Title"] = "Delete Job";
}

<h2>Delete Job</h2>

<h3>Are you sure you want to delete this job?</h3>
<div>
    <h4>Job</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.JobTitle)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.JobTitle)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.JobDescription)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.JobDescription)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RequiredProfiles)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RequiredProfiles)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApplicationDeadline)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApplicationDeadline)
        </dd>
    </dl>

    <form asp-action="DeleteConfirmed">
        <input type="hidden" asp-for="JobId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ASP_GCH1108/Views/JobLists/Details.cshtml
@model JobList

@{
    ViewData["Title"] = "Job Details";
}

<h2 class="my-4">Job Details</h2>

<div>
    <h4>Job</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.JobTitle)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.JobTitle)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.JobDescription)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.JobDescription)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.RequiredProfiles)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.RequiredProfiles)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.ApplicationDeadline)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.ApplicationDeadline)
        </dd>
        <dt class="col-sm-3">
            Status
        </dt>
        <dd class="col-sm-9">
            @(Model.status ? "Allowed" : "Not Allowed")
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.JobId" class="btn btn-primary">Edit</a>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

ASP_GCH1108/Views/JobLists/DetailsAdmin.cshtml
@model ASP_GCH1108.Models.JobList

@{
    ViewData["Title"] = "Job Application Details";
}

<div class="container">
    <h2 class="text-center mt-5">@Model.UserName</h2>

    <div class="card mt-4">
        <div class="card-header">
            <h3>User Id: @Model.UserId</h3>
        </div>
        <div class="card-body">
            <h5 class="card-title">Title: @Model.JobTitle</h5>
            <p class="card-text">Deadline: @Model.ApplicationDeadline</p>
            <p class="card-text">Status: @(Model.status == true ? "Accepted" : "Waiting")</p>
        </div>
    </div>
</div>

<style>
    .container {
        max-width: 800px;
        margin: auto;
    }

    .card {
        border: 1px solid #ddd;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
    }

    .card-header {
        background-color: #007bff;
        color: white;
    }

    .card-body {
        background-color: #f8f9fa;
    }

    .text-center {
        text-align: center;
    }

    .mt-4 {
        margin-top: 1.5rem;
    }

    .mt-5 {
        margin-top: 3rem;
    }
</style>

ASP_GCH1108/Views/JobLists/Edit.cshtml
@model JobList

@{
    ViewData["Title"] = "Edit Job";
}

<h2 class="my-4">Edit Job</h2>

<form asp-action="Edit" class="needs-validation" novalidate>
    <input type="hidden" asp-for="JobId" />
    <div class="mb-3">
        <label asp-for="JobTitle" class="form-label">Job Title</label>
        <input asp-for="JobTitle" class="form-control" required />
        <div class="invalid-feedback">
            @Html.ValidationMessageFor(model => model.JobTitle)
        </div>
    </div>
    <div class="mb-3">
        <label asp-for="JobDescription" class="form-label">Job Description</label>
        <input asp-for="JobDescription" class="form-control" required />
        <div class="invalid-feedback">
            @Html.ValidationMessageFor(model => model.JobDescription)
        </div>
    </div>
    <div class="mb-3">
        <label asp-for="RequiredProfiles" class="form-label">Required Profiles</label>
        <input asp-for="RequiredProfiles" class="form-control" required />
        <div class="invalid-feedback">
            @Html.ValidationMessageFor(model => model.RequiredProfiles)
        </div>
    </div>
    <div class="mb-3">
        <label asp-for="ApplicationDeadline" class="form-label">Application Deadline</label>
        <input asp-for="ApplicationDeadline" class="form-control" type="date" required />
        <div class="invalid-feedback">
            @Html.ValidationMessageFor(model => model.ApplicationDeadline)
        </div>
    </div>
    <div class="mb-3">
        <button type="submit" class="btn btn-primary">Save</button>
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </div>
</form>
<br /><br /><br />

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        (function () {
            'use strict';
            window.addEventListener('load', function () {
                var forms = document.getElementsByClassName('needs-validation');
                var validation = Array.prototype.filter.call(forms, function (form) {
                    form.addEventListener('submit', function (event) {
                        if (form.checkValidity() === false) {
                            event.preventDefault();
                            event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                    }, false);
                });
            }, false);
        })();
    </script>
}

ASP_GCH1108/Views/JobLists/Index.cshtml
@model IEnumerable<JobList>

@{
    ViewData["Title"] = "Job List";
}

<h2>Job List</h2>

<table class="table table-striped table-bordered">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.JobTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobDescription)
            </th>
            <th>
                Status
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.JobTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.JobDescription)
                </td>
                <td>
                    @(item.status ? "Allowed" : "Not Allowed")
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.JobId" class="btn btn-primary">Edit</a>
                    <a asp-action="Details" asp-route-id="@item.JobId" class="btn btn-info">Details</a>
                    <form asp-action="Delete" method="post" style="display:inline;">
                        <input type="hidden" name="id" value="@item.JobId" />
                        <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this job?');">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>