ASP_GCH1108/Controllers/JobListsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using ASP_GCH1108.Data;
using ASP_GCH1108.Models;
using Microsoft.AspNetCore.Authorization;

public class JobListsController : Controller
{
    private readonly UserManager<IdentityUser> _userManager;
    private readonly ApplicationDbContext _context;

    public JobListsController(UserManager<IdentityUser> userManager, ApplicationDbContext context)
    {
        _userManager = userManager;
        _context = context;
    }

    [Authorize(Roles = "Employer")]
    public async Task<IActionResult> Index()
    {
        string UserName = _userManager.GetUserName(User);
        var jobLists = await _context.JobList.Where(j => j.UserName.Equals(UserName)).ToListAsync();
        return View(jobLists);
    }

    [Authorize(Roles = "JobSeeker")]
    public async Task<IActionResult> AvailableJobs()
    {
        var jobLists = await _context.JobList.Where(j => j.status).ToListAsync();
        return View(jobLists);
    }

    [Authorize(Roles = "Employer")]
    public IActionResult Create()
    {
        return View();
    }

    [Authorize(Roles = "Employer")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(JobList jobList)
    {
        if (ModelState.IsValid)
        {
            jobList.UserId = _userManager.GetUserId(User);
            jobList.UserName = _userManager.GetUserName(User);
            jobList.status = false;
            _context.Add(jobList);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        return View(jobList);
    }

    [Authorize(Roles = "Employer")]
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var jobList = await _context.JobList.FindAsync(id);
        if (jobList == null)
        {
            return NotFound();
        }
        return View(jobList);
    }

    [Authorize(Roles = "Employer")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("JobId,JobTitle,JobDescription,RequiredQualifications,ApplicationDeadline")] JobList jobList)
    {
        if (id != jobList.JobId)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                var existingJob = await _context.JobList.FindAsync(id);
                if (existingJob == null)
                {
                    return NotFound();
                }

                existingJob.JobTitle = jobList.JobTitle;
                existingJob.JobDescription = jobList.JobDescription;
                existingJob.RequiredProfiles = jobList.RequiredProfiles;
                existingJob.ApplicationDeadline = jobList.ApplicationDeadline;

                _context.Update(existingJob);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!JobListExists(jobList.JobId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        return View(jobList);
    }

    [Authorize(Roles = "Employer")]
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var jobList = await _context.JobList
            .FirstOrDefaultAsync(m => m.JobId == id);
        if (jobList == null)
        {
            return NotFound();
        }

        return View(jobList);
    }

    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = "Employer")]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var jobList = await _context.JobList.FindAsync(id);
        _context.JobList.Remove(jobList);
        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> Allow(int id)
    {
        var jobList = await _context.JobList.FindAsync(id);
        if (jobList == null)
        {
            return NotFound();
        }

        jobList.status = true;
        _context.Update(jobList);
        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(AdminManager));
    }

    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> DetailsAdmin(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var jobList = await _context.JobList
            .FirstOrDefaultAsync(m => m.JobId == id);
        if (jobList == null)
        {
            return NotFound();
        }

        return View(jobList);
    }

    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> AdminManager()
    {
        return View(await _context.JobList.Where(j => j.status == false).ToListAsync());
    }

    [HttpPost, ActionName("AdminDeleteConfirmed")]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> AdminDeleteConfirmed(int id)
    {
        var jobList = await _context.JobList.FindAsync(id);
        _context.JobList.Remove(jobList);
        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(AdminManager));
    }

    private bool JobListExists(int id)
    {
        return _context.JobList.Any(e => e.JobId == id);
    }
}

ASP_GCH1108/Controllers/ProfilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ASP_GCH1108.Data;
using ASP_GCH1108.Models;
using Microsoft.AspNetCore.Identity;

namespace ASP_GCH1108.Controllers
{
    public class ProfilesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public ProfilesController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Profiles
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Profile.Include(p => p.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Profiles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var profile = await _context.Profile
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.ProfileId == id);
            if (profile == null)
            {
                return NotFound();
            }

            return View(profile);
        }

        // GET: Profiles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Profiles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProfileId,Name,PhoneNumber,Address,BirthDay,Height,Weight,UserId")] Profile profile)
        {
            if (ModelState.IsValid)
            {
                profile.UserId = _userManager.GetUserId(User);
                _context.Add(profile);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(profile);
        }

        // GET: Profiles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var profile = await _context.Profile.FindAsync(id);
            if (profile == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", profile.UserId);
            return View(profile);
        }

        // POST: Profiles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProfileId,Name,PhoneNumber,Address,BirthDay,Height,Weight,UserId")] Profile profile)
        {
            if (id != profile.ProfileId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(profile);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProfileExists(profile.ProfileId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", profile.UserId);
            return View(profile);
        }

        // GET: Profiles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var profile = await _context.Profile
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.ProfileId == id);
            if (profile == null)
            {
                return NotFound();
            }

            return View(profile);
        }

        // POST: Profiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var profile = await _context.Profile.FindAsync(id);
            if (profile != null)
            {
                _context.Profile.Remove(profile);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProfileExists(int id)
        {
            return _context.Profile.Any(e => e.ProfileId == id);
        }
    }
}

ASP_GCH1108/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP_GCH1108</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/ASP_GCH1108.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASP_GCH1108</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">User Manager</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="JobLists" asp-action="AdminManager">JobLists Manager</a>
                            </li>
                        }
                        @if (User.IsInRole("Employer"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="JobLists" asp-action="Index">View JobList</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="JobLists" asp-action="Create">Create JobList</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="JobApplications" asp-action="EmployerView">JobApplication Manager</a>
                            </li>
                        }
                        @if (User.IsInRole("JobSeeker"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="JobApplications" asp-action="Index">View JobApplications</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Profiles" asp-action="Index">Profile Manager</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="JobLists" asp-action="AvailableJobs">View jobListings</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <br /><br />
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ASP_GCH1108 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>